version: "3.8"
services:
  videocms:
    image: kirari04/videocms:beta
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Generate with: openssl rand -base64 32
      StorageEncryptionKey: "${StorageEncryptionKey:-}"
    volumes:
      - ./videos:/app/videos
      - ./database:/app/database
